<template>
  <section>
    <div class="section-heading"><div><h2>{{ tr('通用页面管理','Page manager') }}</h2><p>{{ tr('管理 source 下的 index.md 与独立 Markdown 页面，并维护真实主题菜单顺序。','Manage index.md and standalone Markdown pages under source, plus the active theme menu order.') }}</p></div><button class="btn btn-primary" @click="creating=!creating">＋ {{ tr('新建页面','New page') }}</button></div>
    <div v-if="creating" class="card page-create-card"><div class="card-title">{{ tr('创建独立页面','Create page') }}</div><div class="form-row"><div class="form-group"><label>{{ tr('标题','Title') }}</label><input v-model="form.title"></div><div class="form-group"><label>{{ tr('源码路径','Source path') }}</label><input v-model="form.path" placeholder="projects/index.md"></div></div><div class="form-row"><div class="form-group"><label>{{ tr('Hexo Scaffold','Hexo scaffold') }}</label><select v-model="form.scaffold"><option value="">{{ tr('不使用模板','No scaffold') }}</option><option v-for="item in scaffolds" :key="item.name" :value="item.name">{{ item.name }}</option></select></div><div class="form-group"><label>{{ tr('页面布局','Layout') }}</label><input v-model="form.layout" placeholder="page"></div></div><div class="btn-group"><button class="btn btn-primary" :disabled="creatingBusy||!form.title.trim()||!form.path.trim()" @click="create">{{ tr('创建并编辑','Create and edit') }}</button><button class="btn btn-outline" @click="creating=false">{{ tr('取消','Cancel') }}</button></div></div>
    <div class="pages-grid">
      <div class="card"><div class="card-title">{{ tr('页面文件','Page files') }} · {{ pages.length }}</div><div v-if="loading" class="loading">{{ tr('加载中...','Loading...') }}</div><div v-else-if="!pages.length" class="empty">{{ tr('暂无独立页面','No standalone pages') }}</div><div v-else class="page-list"><article v-for="page in pages" :key="page.id" class="page-list-item"><div><strong>{{ page.title }}</strong><code>{{ page.path }}</code><small>{{ page.permalink }} · {{ page.layout||'page' }}</small></div><div class="btn-group"><button class="btn btn-outline btn-sm" @click="$emit('edit',page.id)">{{ tr('编辑','Edit') }}</button><button class="btn btn-danger btn-sm" @click="remove(page)">{{ tr('删除','Delete') }}</button></div></article></div></div>
      <div class="card"><div class="card-title">{{ tr('主题菜单顺序','Theme menu order') }}</div><p class="text-sm text-muted menu-config-path">{{ menu.configPath }}</p><div v-if="!menu.items?.length" class="empty">{{ tr('当前主题未配置菜单','No theme menu entries found') }}</div><div v-else class="menu-order-list"><div v-for="(item,index) in menu.items" :key="item.label" class="menu-order-item"><span class="menu-drag-index">{{ index+1 }}</span><div><strong>{{ item.label }}</strong><small>{{ item.path }}</small></div><div class="btn-group"><button class="btn btn-outline btn-sm" :disabled="index===0" @click="move(index,-1)">↑</button><button class="btn btn-outline btn-sm" :disabled="index===menu.items.length-1" @click="move(index,1)">↓</button></div></div></div><button v-if="menu.items?.length" class="btn btn-primary menu-save" :disabled="menuSaving" @click="saveMenu">{{ menuSaving?tr('保存中...','Saving...'):tr('保存菜单顺序','Save menu order') }}</button><p class="text-sm text-muted">{{ tr('保存后需重建或重启 Hexo 才能让主题菜单生效。','Rebuild or restart Hexo after saving so the theme reloads the menu.') }}</p></div>
    </div>
  </section>
</template>

<script setup>
import { onMounted, reactive, ref } from 'vue';
import { api } from '../api/client';
import { useI18n } from '../i18n';
const {tr,errorMessage}=useI18n();const emit=defineEmits(['edit','notify','request-confirm']);
const pages=ref([]),menu=ref({items:[],revision:'',configPath:''}),scaffolds=ref([]),loading=ref(false),creating=ref(false),creatingBusy=ref(false),menuSaving=ref(false);
const form=reactive({title:'',path:'',scaffold:'page',layout:'page'});
async function load(){loading.value=true;try{const [data,templates]=await Promise.all([api.get('/pages'),api.get('/scaffolds')]);pages.value=data.items||[];menu.value=data.menu||{items:[]};scaffolds.value=templates.items||[];if(!scaffolds.value.some(item=>item.name===form.scaffold))form.scaffold=scaffolds.value[0]?.name||'';}catch(error){emit('notify',errorMessage(error),'error');}finally{loading.value=false;}}
async function create(){creatingBusy.value=true;try{const data=await api.post('/pages',{...form,title:form.title.trim(),path:form.path.trim()});emit('notify',tr('页面已创建','Page created'),'success');creating.value=false;emit('edit',data.id);}catch(error){emit('notify',errorMessage(error),'error');}finally{creatingBusy.value=false;}}
function remove(page){emit('request-confirm',tr('删除页面','Delete page'),tr('确定删除“{title}”吗？文件会移入回收站。','Delete “{title}”? The file will be moved to trash.',{title:page.title}),async()=>{try{await api.del('/pages/'+page.id,page.revision);emit('notify',tr('页面已移入回收站','Page moved to trash'),'success');load();}catch(error){emit('notify',errorMessage(error),'error');}});}
function move(index,delta){const items=menu.value.items.slice();const target=index+delta;[items[index],items[target]]=[items[target],items[index]];menu.value={...menu.value,items};}
async function saveMenu(){menuSaving.value=true;try{const saved=await api.put('/pages/menu',{items:menu.value.items.map(({label,path,icon})=>({label,path,icon})),revision:menu.value.revision});menu.value={...menu.value,...saved};emit('notify',tr('主题菜单顺序已保存','Theme menu order saved'),'success');}catch(error){emit('notify',errorMessage(error),'error');}finally{menuSaving.value=false;}}
onMounted(load);
</script>
