<template>
  <section>
    <div class="section-heading"><div><h2>{{ tr('发布中心','Publishing center') }}</h2><p>{{ tr('在日历中查看计划，跟踪生成与部署进度，并处理失败重试。','View plans on a calendar, track build and deploy progress, and retry failures.') }}</p></div><div class="btn-group"><button class="btn btn-outline" @click="load">{{ tr('刷新','Refresh') }}</button><button class="btn btn-primary" :disabled="starting" @click="startCommand('deploy')">{{ tr('立即部署','Deploy now') }}</button></div></div>
    <div class="publishing-summary"><div class="stat-card"><div class="num">{{ activeSchedules }}</div><div class="label">{{ tr('待发布','Scheduled') }}</div></div><div class="stat-card"><div class="num">{{ failedCount }}</div><div class="label">{{ tr('失败待处理','Failed') }}</div></div><div class="stat-card"><div class="num">{{ runningJobs }}</div><div class="label">{{ tr('运行中任务','Running jobs') }}</div></div></div>
    <div class="publishing-layout">
      <div class="card calendar-card"><div class="calendar-head"><button class="btn btn-outline btn-sm" @click="monthOffset--">←</button><strong>{{ monthTitle }}</strong><button class="btn btn-outline btn-sm" @click="monthOffset++">→</button></div><div class="calendar-grid calendar-week"><span v-for="day in week" :key="day">{{day}}</span></div><div class="calendar-grid"><div v-for="cell in calendar" :key="cell.key" class="calendar-day" :class="{muted:!cell.current,today:cell.today}"><b>{{cell.day}}</b><button v-for="task in cell.tasks" :key="task.id" :class="'calendar-task task-'+task.status" @click="selectedSchedule=task">{{task.title}}</button></div></div></div>
      <div class="card"><div class="card-title">{{ tr('计划任务','Schedule details') }}</div><div v-if="!selectedSchedule" class="empty">{{ tr('从日历选择一个任务','Select a task from the calendar') }}</div><template v-else><h3>{{selectedSchedule.title}}</h3><p class="text-sm text-muted">{{formatDateTime(selectedSchedule.publishAt)}} · {{statusLabel(selectedSchedule.status)}}</p><p v-if="selectedSchedule.error" class="task-error">{{selectedSchedule.error}}</p><div class="btn-group"><button v-if="['failed','cancelled'].includes(selectedSchedule.status)" class="btn btn-primary btn-sm" @click="retrySchedule(selectedSchedule)">{{tr('立即重试','Retry now')}}</button><button v-if="['scheduled','retrying','failed'].includes(selectedSchedule.status)" class="btn btn-danger btn-sm" @click="cancelSchedule(selectedSchedule)">{{tr('取消任务','Cancel')}}</button></div><div class="timeline"><div v-for="(entry,index) in selectedSchedule.history||[]" :key="index"><i></i><span><strong>{{statusLabel(entry.status)}}</strong><small>{{formatDateTime(entry.at)}} · {{entry.message}}</small></span></div></div></template></div>
    </div>
      <div class="card"><div class="card-title job-history-title"><span>{{ tr('部署与生成历史','Deploy and build history') }}</span><div class="btn-group"><button class="btn btn-outline btn-sm" :disabled="starting" @click="startCommand('generate')">{{tr('生成','Generate')}}</button><button class="btn btn-outline btn-sm" :disabled="starting" @click="startCommand('rebuild')">{{tr('重建','Rebuild')}}</button></div></div><div v-if="loading" class="loading">{{tr('加载中...','Loading...')}}</div><div v-else class="job-history"><article v-for="job in jobs" :key="job.id" class="job-history-item" :class="'job-'+job.status"><div class="job-history-head"><div><strong>{{job.command}}</strong><small>{{formatDateTime(job.createdAt)}} · {{statusLabel(job.status)}}</small></div><span>{{job.progress||0}}%</span></div><div class="progress-track"><i :style="{width:(job.progress||0)+'%'}"></i></div><div class="command-job-log"><div v-for="(entry,index) in job.logs||[]" :key="index"><time>{{formatTime(entry.at)}}</time><span>{{entry.message}}</span></div></div><div class="btn-group job-actions"><button v-if="['queued','running','cancelling'].includes(job.status)" class="btn btn-danger btn-sm" @click="cancelJob(job)">{{tr('取消','Cancel')}}</button><button v-if="['failed','cancelled'].includes(job.status)&&['generate','deploy','clean','rebuild'].includes(job.command)" class="btn btn-outline btn-sm" @click="retryJob(job)">{{tr('重试','Retry')}}</button></div></article><div v-if="!jobs.length" class="empty">{{tr('暂无任务历史','No job history')}}</div></div></div>
  </section>
</template>

<script setup>
import { computed, onBeforeUnmount, onMounted, ref } from 'vue';
import { api } from '../api/client';
import { useI18n } from '../i18n';
const {locale,tr,errorMessage}=useI18n();const emit=defineEmits(['notify']);
const schedules=ref([]),jobs=ref([]),loading=ref(false),starting=ref(false),monthOffset=ref(0),selectedSchedule=ref(null);let timer;
const activeSchedules=computed(()=>schedules.value.filter(item=>['scheduled','retrying','running'].includes(item.status)).length);const failedCount=computed(()=>schedules.value.filter(item=>item.status==='failed').length+jobs.value.filter(item=>item.status==='failed').length);const runningJobs=computed(()=>jobs.value.filter(item=>['queued','running','cancelling'].includes(item.status)).length);
const viewedMonth=computed(()=>{const date=new Date();date.setDate(1);date.setMonth(date.getMonth()+monthOffset.value);return date;});const monthTitle=computed(()=>viewedMonth.value.toLocaleDateString(locale.value==='en'?'en-US':'zh-CN',{year:'numeric',month:'long'}));const week=computed(()=>locale.value==='en'?['Sun','Mon','Tue','Wed','Thu','Fri','Sat']:['日','一','二','三','四','五','六']);
const calendar=computed(()=>{const first=new Date(viewedMonth.value);first.setDate(1-first.getDay());const today=new Date().toDateString();return Array.from({length:42},(_,index)=>{const date=new Date(first);date.setDate(first.getDate()+index);const key=date.toISOString().slice(0,10);return{key,day:date.getDate(),current:date.getMonth()===viewedMonth.value.getMonth(),today:date.toDateString()===today,tasks:schedules.value.filter(item=>String(item.publishAt||item.nextAttemptAt).slice(0,10)===key)};});});
async function load(silent=false){if(!silent)loading.value=true;try{const [scheduled,history]=await Promise.all([api.get('/schedules'),api.get('/commands/jobs?limit=50')]);schedules.value=scheduled.items||[];jobs.value=history.items||[];if(selectedSchedule.value)selectedSchedule.value=schedules.value.find(item=>item.id===selectedSchedule.value.id)||null;}catch(error){if(!silent)emit('notify',errorMessage(error),'error');}finally{loading.value=false;}}
async function startCommand(command){starting.value=true;try{await api.post('/commands/'+command);emit('notify',tr('任务已进入队列','Job queued'),'success');await load(true);}catch(error){emit('notify',errorMessage(error),'error');}finally{starting.value=false;}}
async function cancelJob(job){try{await api.post('/commands/jobs/'+job.id+'/cancel');await load(true);}catch(error){emit('notify',errorMessage(error),'error');}}
async function retryJob(job){try{await api.post('/commands/jobs/'+job.id+'/retry');emit('notify',tr('已创建重试任务','Retry job created'),'success');await load(true);}catch(error){emit('notify',errorMessage(error),'error');}}
async function cancelSchedule(item){try{await api.del('/schedules/'+item.id);emit('notify',tr('定时任务已取消','Schedule cancelled'),'success');await load(true);}catch(error){emit('notify',errorMessage(error),'error');}}
async function retrySchedule(item){try{await api.post('/schedules/'+item.id+'/retry',{});emit('notify',tr('定时任务将立即重试','Schedule will retry now'),'success');await load(true);}catch(error){emit('notify',errorMessage(error),'error');}}
function statusLabel(value){return({queued:tr('排队中','Queued'),running:tr('执行中','Running'),cancelling:tr('取消中','Cancelling'),completed:tr('已完成','Completed'),failed:tr('失败','Failed'),cancelled:tr('已取消','Cancelled'),scheduled:tr('计划中','Scheduled'),retrying:tr('等待重试','Retrying')})[value]||value;}
function formatDateTime(value){return value?new Date(value).toLocaleString(locale.value==='en'?'en-US':'zh-CN'):'';}function formatTime(value){return value?new Date(value).toLocaleTimeString(locale.value==='en'?'en-US':'zh-CN',{hour12:false}):'';}
onMounted(()=>{load();timer=setInterval(()=>{if(runningJobs.value||activeSchedules.value)load(true);},2000);});onBeforeUnmount(()=>clearInterval(timer));
</script>
