<template><section><div class="toolbar"><h2>{{tr('统一恢复中心','Recovery center')}}</h2><button class="btn btn-outline" @click="load">{{tr('刷新','Refresh')}}</button></div><p>{{tr('可定位备份占用','Located backup storage')}}：{{formatSize(totalBytes)}}</p><p class="text-sm text-muted">{{note}}</p><input v-model="search" :placeholder="tr('按文件或备份类型筛选','Filter by file or backup type')"><div v-if="selected" class="card"><h3>{{selected.source}}</h3><TextDiff v-if="selected.encoding==='utf8'" :before="selected.current" :after="selected.content"/><div v-else><div v-if="imageMime" class="recovery-images"><figure><figcaption>{{tr('当前文件','Current file')}}</figcaption><img v-if="selected.current" :src="'data:'+imageMime+';base64,'+selected.current" alt="Current"></figure><figure><figcaption>{{tr('备份原图','Backup image')}}</figcaption><img :src="'data:'+imageMime+';base64,'+selected.content" alt="Backup"></figure></div><p>{{tr('二进制原图恢复：将替换当前文件，当前文件会先保存到历史。','Binary restore replaces the current file after saving it to history.')}} {{selected.size}} B</p></div><div class="btn-group"><button class="btn btn-warning" @click="restore">{{tr('确认恢复此文件','Restore this file')}}</button><button class="btn btn-outline" @click="selected=null">{{tr('取消','Cancel')}}</button></div></div><div class="table-wrap"><table><thead><tr><th>{{tr('文件 / 类型','File / type')}}</th><th>{{tr('保存时间','Saved at')}}</th><th>{{tr('保留策略','Retention')}}</th><th></th></tr></thead><tbody><tr v-for="item in filtered" :key="item.id"><td>{{item.source}}<small> · {{item.group}}</small></td><td>{{new Date(item.createdAt).toLocaleString()}}</td><td>{{item.policy}}</td><td><button class="btn btn-outline btn-sm" @click="preview(item)">{{tr('预览恢复差异','Preview restore diff')}}</button></td></tr></tbody></table></div><p v-if="filtered.length===0">{{tr('暂无匹配的备份','No matching backups')}}</p></section></template>
<script setup>
import {computed,onMounted,ref} from 'vue';import {api} from '../api/client';import TextDiff from '../components/TextDiff.vue';import {useI18n} from '../i18n';
const {tr,errorMessage}=useI18n();const emit=defineEmits(['notify']);const items=ref([]),search=ref(''),selected=ref(null),totalBytes=ref(0),note=ref('');const filtered=computed(()=>items.value.filter(item=>(item.source+' '+item.group).toLowerCase().includes(search.value.toLowerCase())));
const imageMime=computed(()=>{if(!selected.value||selected.value.encoding!=='base64')return '';const extension=selected.value.source.split('.').at(-1).toLowerCase();return ({png:'image/png',jpg:'image/jpeg',jpeg:'image/jpeg',gif:'image/gif',webp:'image/webp',avif:'image/avif',bmp:'image/bmp'})[extension]||'';});
function formatSize(bytes){return bytes<1024?bytes+' B':bytes<1048576?(bytes/1024).toFixed(2)+' KiB':(bytes/1048576).toFixed(2)+' MiB';}
async function load(){try{const data=await api.get('/recovery');items.value=data.items;totalBytes.value=data.totalBytes;note.value=data.note;}catch(error){emit('notify',errorMessage(error),'error');}}
async function preview(item){try{selected.value=await api.get('/recovery/'+item.id);}catch(error){emit('notify',errorMessage(error),'error');}}
async function restore(){try{const data=await api.post('/recovery/'+selected.value.id+'/restore',{revision:selected.value.currentRevision});emit('notify',data.restartRequired?tr('已恢复配置，请重启 Hexo 生效','Configuration restored. Restart Hexo to apply it'):data.refreshed===false?tr('已恢复文件，但 Hexo 刷新失败','File restored; Hexo refresh failed'):tr('文件已恢复','File restored'),data.refreshed===false?'warning':'success');selected.value=null;await load();}catch(error){emit('notify',errorMessage(error),'error');}}
onMounted(load);
</script>

<style scoped>.recovery-images{display:grid;grid-template-columns:1fr 1fr;gap:12px}.recovery-images img{max-width:100%;max-height:300px;object-fit:contain}.recovery-images figure{margin:0}</style>
