<template><details class="card" @toggle="load"><summary>{{tr('本文章资源与反向引用','Post assets and references')}}</summary><p class="text-sm text-muted">{{tr('公共媒体按已保存文章中的引用筛选；文章资源目录使用 asset_img 插入。','Shared media is filtered by references in the saved post. Post assets use asset_img tags.')}}</p><div v-if="renamePlan"><p>{{renamePlan.scope}} · {{renamePlan.count}} {{tr('处引用','references')}}</p><TextDiff :before="renamePlan.before" :after="renamePlan.after"/><button class="btn btn-warning" @click="confirmRename">{{tr('确认重命名并更新文章','Rename and update post')}}</button><button class="btn btn-outline" @click="renamePlan=null">{{tr('取消','Cancel')}}</button></div><input v-if="assets.enabled" type="file" multiple @change="upload"><div v-for="item in assets.items||[]" :key="item.name" class="toolbar"><span>{{item.name}} · {{item.size}} B</span><div class="btn-group"><button class="btn btn-outline btn-sm" @click="$emit('insert',item.tag)">{{tr('插入 asset_img','Insert asset_img')}}</button><button class="btn btn-outline btn-sm" @click="rename(item)">{{tr('重命名','Rename')}}</button><button class="btn btn-danger btn-sm" @click="remove(item)">{{tr('删除前查看影响','Review deletion')}}</button></div></div><div v-for="item in shared" :key="item.name" class="text-sm">{{item.name}} · {{item.referenceCount}} {{tr('处引用','references')}}</div><p v-if="!assets.enabled">{{tr('站点尚未启用 post_asset_folder，可继续使用公共媒体。','post_asset_folder is disabled; shared media remains available.')}}</p></details></template>
<script setup>
import {ref} from 'vue';import TextDiff from './TextDiff.vue';import {api} from '../api/client';import {useI18n} from '../i18n';
const {tr,errorMessage}=useI18n();const props=defineProps({postId:{type:String,required:true}});const emit=defineEmits(['notify','insert']);const assets=ref({}),shared=ref([]),renamePlan=ref(null);
async function load(event){if(event&&event.target&&!event.target.open)return;try{assets.value=await api.get('/posts/'+props.postId+'/assets');shared.value=(await api.get('/media?per_page=100&source='+encodeURIComponent(assets.value.source))).files||[];}catch(error){emit('notify',errorMessage(error),'error');}}
async function upload(event){const form=new FormData();for(const file of event.target.files||[])form.append('file',file);try{await api.upload('/posts/'+props.postId+'/assets',form);await load();}catch(error){emit('notify',errorMessage(error),'error');}finally{event.target.value='';}}
async function remove(item){try{const endpoint='/posts/'+props.postId+'/assets/'+encodeURIComponent(item.name);const plan=await api.get(endpoint+'/delete-preview');if(!window.confirm(plan.scope+'\n'+plan.references.map(ref=>ref.source+':'+ref.line+' '+ref.text).join('\n')+'\n'+tr('确定删除此资源？','Delete this asset?')))return;await api.del(endpoint,plan.revision);await load();}catch(error){emit('notify',errorMessage(error),'error');}}
async function rename(item){const name=window.prompt(tr('新文件名','New file name'),item.name.split('/').at(-1));if(!name)return;try{const endpoint='/posts/'+props.postId+'/assets/'+encodeURIComponent(item.name);renamePlan.value={...await api.post(endpoint+'/rename-preview',{name}),endpoint,requestedName:name};}catch(error){emit('notify',errorMessage(error),'error');}}
async function confirmRename(){try{await api.put(renamePlan.value.endpoint+'/rename',{name:renamePlan.value.requestedName,revision:renamePlan.value.revision});renamePlan.value=null;emit('notify',tr('资源与服务器文章引用已更新；编辑器保存时若提示冲突，请合并新引用。','Asset and saved references updated. Merge the new references if the editor reports a conflict.'),'success');await load();}catch(error){emit('notify',errorMessage(error),'error');}}
</script>

<style scoped>.card{padding:12px 16px}</style>
